trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'Azure subscription 1 (05f3eee7-1378-45df-b538-4b7aaaf881c9)'
    appName: 'sistemalocacao'
    resourceGroupName: 'FernandoDefault'
    connectionStrings: |
      "ConnectionStrings": {
          "DefaultConnection": "Server=localhost,3306;Database=SistemaLocacao;User Id=root;Password=rakk6p4J@kYb"
        }

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1 (05f3eee7-1378-45df-b538-4b7aaaf881c9)'
    appType: 'webAppLinux'
    WebAppName: 'sistemalocacao'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|6.0'